### ISSUE TITLE
CKEditor 5 v11.0.0 is now compatible with Electron

### ISSUE THREAD

**Issue by Reinmar** [li-rongcheng/electron-angular5-ckeditor5#1]
Hi there! It's great to see you tried CKEditor 5 with Angular and Electron.

I'm happy to let you know the latest release of [CKEditor 5 is now compatible with Electron](https://github.com/ckeditor/ckeditor5/issues/1121) so you may want to update your test. BTW, we even tested that [real-time collaboration editing](https://twitter.com/ckeditor/status/1016627687568363520) works fine in Electron.

Another thing is that we're working hard on [CKEditor 5 component for Angular](https://github.com/ckeditor/ckeditor5-angular). We plan to publish the first version of it to npm very soon but you can already test it from GH.

**Comment by lifewithcoffee** [comment]
Great work! Many thanks for letting me know. I'll definitely try it soon.
